language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.4 DJANGO_VERSION_MIN=1.4 DJANGO_VERSION_MAX=1.5
  - DJANGO=1.6 DJANGO_VERSION_MIN=1.6 DJANGO_VERSION_MAX=1.7
  - DJANGO=1.7 DJANGO_VERSION_MIN=1.7 DJANGO_VERSION_MAX=1.8
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.7 DJANGO_VERSION_MIN=1.7 DJANGO_VERSION_MAX=1.8
install:
  - pip install -q "Django>=$DJANGO_VERSION_MIN,<$DJANGO_VERSION_MAX"
  - pip install -q django-nose==1.2 coverage coveralls flake8
  - pip install -e .
script:
  - flake8 scraper  --exclude=*/migrations/*,*test*
  - coverage run --source='./' --omit=*/migrations/*,*test* run_tests.py
after_script:
  - coveralls
